---
title: "lesson3"
output: html_document
---

```{r}
library(ggplot2)
```

Histogram of people's birthdays
```{r}
setwd("/Users/Nick/Documents/udacity/projects/data_analysis_with_r/")
list.files()
pf = read.delim("pseudo_facebook.tsv", sep="\t")
names(pf)
qplot(x=dob_day, data=pf) + 
  scale_x_discrete(breaks=1:31)
```

Faceting
```{r}
ggplot(data = pf, aes(x = dob_day)) + 
  geom_histogram() + 
  scale_x_discrete(breaks = 1:31) + 
  facet_wrap(~dob_month, ncol=4)
```

Adjusting axes
```{r}
ggplot(data = subset(pf, !is.na(gender)), aes(x = friend_count)) + 
  geom_histogram() + scale_x_continuous(limits = c(0, 1000), breaks=seq(0, 1000, 10)) + 
  facet_wrap(~gender)
```

Table based on data
Table of summarized friend count statistics by gender
```{r}
table(pf$gender)
by(pf$friend_count, pf$gender, summary)
```

Tenure
```{r}
ggplot(data=pf, aes(x=tenure/365)) +
  geom_histogram(color=I("black"), fill=I("#099DD9")) + 
  scale_x_continuous(breaks=seq(1,7,1)) + 
  xlab("Number of years using Facebook") + ylab("Number of Users")
```

Ages
```{r}
ggplot(data=subset(pf, !is.na(gender)), aes(x=age, fill=gender)) +
  geom_histogram(color=I("white"), binwidth=2) +
  xlab("Age of User (years)") + ylab("Number of Users") +
  facet_wrap(~gender)
```

Transforming data
```{r}
ggplot(data=pf, aes(x=friend_count)) + geom_histogram()
```

Multiple plots
```{r}
library(gridExtra)
plot1 = ggplot(data=pf, aes(x=friend_count)) + geom_histogram()
plot2 = ggplot(data=pf, aes(x=friend_count)) + geom_histogram() + scale_x_log10()
plot3 = ggplot(data=pf, aes(x=friend_count)) + geom_histogram() + scale_x_sqrt()
grid.arrange(plot1, plot2, plot3, ncol=1)
```

Multiple data on one plot
```{r}
ggplot(aes(x = friend_count, y = ..count../sum(..count..)), data = subset(pf, !is.na(gender))) +
  geom_freqpoly(aes(color = gender), binwidth=10) + 
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 100)) +
  xlab('Friend Count') + 
  ylab('Percentage of users with that friend count')
```

Multiple data on one plot, this time with www_likes
```{r}
ggplot(aes(x = www_likes), data = subset(pf, !is.na(gender))) +
  geom_freqpoly(aes(color = gender)) + 
    scale_x_log10() +
  xlab('Likes Online') + 
  ylab('Percentage of users with that friend count')

by(pf$www_likes, pf$gender, sum)
```

Box Plot
```{r}
ggplot(aes(x = gender, y=friend_count), data = subset(pf, !is.na(gender))) + 
  geom_boxplot() + scale_y_continuous(limits=c(0,250))
```

Who initiated more friendships?
```{r}
by(pf$friendships_initiated, pf$gender, summary)
```

Mobile Checkins
```{r}
pf$mobile_check_in <- NA
pf$mobile_check_in <- ifelse(pf$mobile_likes > 0, 1, 0)
pf$mobile_check_in <- factor(pf$mobile_check_in)
summary(pf$mobile_check_in)
sum(pf$mobile_check_in == 1)/(sum(pf$mobile_check_in == 1) + sum(pf$mobile_check_in == 0)) * 100
```






